Master udp connection
gerazo/pipert pull request #38
Opened 2021-02-20 22:48 UTC by baselqyqony

add UDP Connection , with relevant tests

2021-02-22 14:41 UTC, gerazo requested changes
You have opened a PR on this branch which is seemengly a working branch with a lot of history and modifications. I believe that the reason for this PR is to merge the UDP tests into Profiler. However, if this merge gets in, it will bring a lot of history also which is not necessarily wanted.
What is worse that as this working branch had numerous merges from different sources, it is not in sync with master. For instance, the changelog on this PR shows things which already went into master once. So this means that the actual diffs and the actual state is not in sync. Git keeps info on child-parent relationships of commits and thinks that a perfect resolution and merging of all features were done at every merge. So now, it clearly does not know that some changes already went back to master. This means that by merging this branch, we can actually even revert newer changes without knowing it. You should rather:
 - create a separate branch for the PR
 - have this branch fixed by diffing to master and actually resolving the non-diff differences
 However, the latter one does not make sense if this is a working branch where experiments are done.

2021-02-22 14:41 UTC, gerazo commented on test/ProfilerTest.cpp
> +#include <unistd.h>
Please only use headers which are in fact needed for this implementation. It means that you should check the relevant standards and put the headers here according to them... so do not rely on your current platform.

2021-02-22 14:41 UTC, gerazo commented on test/ProfilerTest.cpp
>  #include <cstdio>
Alos try to put these into groups but inside the groups, keep alphabetic order.

2021-02-22 14:41 UTC, gerazo commented on test/ProfilerTest.cpp
> +const std::uint16_t server_port = 8888;
These should all go into anonymous namespace or mysterious things will happen again.

2021-02-22 14:41 UTC, gerazo commented on test/ProfilerTest.cpp
> +TEST(ProfilerTest, TestUdpUsingSchedular) {
Try to keep consistent naming (UDP or Udp?)

2021-02-22 14:41 UTC, gerazo commented on test/ProfilerTest.cpp
> +
We had this HumanPrinter stuf copy-pasted a lot... I am afraid it will not be maintainable... although it is not as important. now.

2021-02-25 08:49 UTC, gerazo commented
Getting better but it is still not good. Please have a look at "Files changed" tab here in the PR page! It shows what changes will get into master. However, some changes do not belong to UDP connection and many of these are already merged into master. If this goes in like that, you will duplicate commits in the commit timeline and everyone will be angry. :)

2021-02-25 10:03 UTC, baselqyqony commented
thank you , I will checkout the file then add the changes not to have wrong code changes info on the commit

2021-03-05 17:19 UTC, gerazo commented
The changeset is still broader than it should be. Feel free to refrok a new branch if you cannot put this in order.

2021-03-09 08:17 UTC, baselqyqony commented
thank you , yes it may has a lot of changes  because i created the udp connection class then they were merged in log analyzer then  I had to merge it back to the branch and add another test after that , should i go to the point before the  first merge and add the last version of UDP class and its tests ?

2021-03-09 10:28 UTC, gerazo commented
It wiil continue on a different branch

2021-03-09 10:28 UTC, closed without merging